modLoader="javafml" #mandatory
loaderVersion = "[0,)"
license="MIT"
[[mods]] #mandatory
modId="create_mechanical_chicken" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create Mechanical Chicken" #mandatory
logoFile="logo.png" #optional
credits="Thanks to the Creators of Create" #optional
authors="oierbravo" #optional
description='''
Simple chicken egg generator
'''
[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId = "create"
    mandatory = true
    versionRange="[6.0.2,6.1.0)"
    ordering = "AFTER"
    side = "BOTH"
